03/Jan/2014 15:00:00  0100 SELECT DISTINCT ?Museum (SAMPLE(?name) as ?name) (SAMPLE(?abstract) as ?abstract) (SAMPLE(?thumbnail) as ?thumbnail) (MAX(?latitude) as ?latitude) (MAX(?longitude) as ?longitude) (SAMPLE(?established) as ?established) (SAMPLE(?website) as ?website) (SAMPLE(?homepage) as ?homepage) (SAMPLE(?wikilink) as ?wikilink) WHERE { ?Museum a dbpedia-owl:Museum ;          dbpprop:name ?name ; dbpedia-owl:abstract ?abstract ; dbpedia-owl:thumbnail ?thumbnail ;  geo:lat ?latitude ; geo:long ?longitude ; dbpprop:established ?established; dbpprop:website ?website ; foaf:homepage ?homepage ; foaf:isPrimaryTopicOf ?wikilink . FILTER(langMatches(lang(?abstract),"ES"))   } GROUP BY ?Museum  LIMIT 10 OFFSET 0


prefix dbp:<http://dbpedia.org/ontology/>
select ?athleteGroupEN (count(?athlete) as ?count) (avg(?age) as ?ageAvg)
    where {
        filter(?age >= 20 && ?age <= 100) .
        {
            select distinct ?athleteGroupEN ?athlete (?deathYear - ?birthYear as ?age)
                where {
                    ?subOfAthlete rdfs:subClassOf dbp:Athlete .
                        ?subOfAthlete rdfs:label ?athleteGroup filter(lang(?athleteGroup) = "en") .
                        bind(str(?athleteGroup) as ?athleteGroupEN)
                        ?athlete a ?subOfAthlete .
                        ?athlete dbp:birthDate ?birth filter(datatype(?birth) = xsd:date) .
                        ?athlete dbp:deathDate ?death filter(datatype(?death) = xsd:date) .
                        bind (strdt(replace(?birth,"^(\\d+)-.*","$1"),xsd:integer) as ?birthYear) .
                        bind (strdt(replace(?death,"^(\\d+)-.*","$1"),xsd:integer) as ?deathYear) .
                }
        }
    } group by ?athleteGroupEN having (count(?athlete) >= 25) order by ?ageAvg


prefix dcterms:<http://purl.org/dc/terms/>
prefix dbr:<http://dbpedia.org/resource/>
select ?showB ?subjCountShowAB ?subjCountShowA ?subjCountShowB (strdt(?subjCountShowAB,xsd:double) / (?subjCountShowA + ?subjCountShowB - ?subjCountShowAB) as ?subjScore)
where
{
  {
    select ?showB ?subjCountShowAB ?subjCountShowA (count(?subject) as ?subjCountShowB)
    where
    {
      ?showB dcterms:subject ?subject .
      {
        select ?showB (count(?subject) as ?subjCountShowAB) ?subjCountShowA
        where
        {
          ?showA dcterms:subject ?subject .
          ?showB dcterms:subject ?subject filter(!sameTerm(?showA,?showB)) .
          {
            select ?showA (count(?subject) as ?subjCountShowA)
            where
            {
              ?showA dcterms:subject ?subject filter(sameTerm(?showA,dbr:Friends)) .
            }
          }
        }
        group by ?showB ?subjCountShowA
      }
    }
    group by ?showB ?subjCountShowAB ?subjCountShowA
  }
}
ORDER BY desc(?subjScore) LIMIT 100

SELECT *
WHERE {
    ?p rdfs:range ?range.
        FILTER regex(?range, "^http://www.w3.org/2001/XMLSchema#", "i")
        {
            SELECT DISTINCT ?p
                WHERE {
                    ?p rdf:type rdf:Property.
                }
            #limit 1000
        }
} ORDER BY ?range

SELECT *
WHERE
{
  ?p rdfs:range ?range. FILTER regex(?range, "^http://www.w3.org/2001/XMLSchema#", "i")
  {
    SELECT ?p
    WHERE { [] a dbo:Person; ?p [].
      {
        SELECT DISTINCT ?p
        WHERE
        {
          ?p rdf:type rdf:Property.
        }
      }
    }
  }
}

digraph{
  "?Electronic_rock"->"?Grindcore"[label="dbo:musicSubgenre"];
  "?Noise_pop"->"?Group429"[label="dbp:localScenes"];
  "?Noise_rock"->"?Noise_pop"[label="dbp:fusiongenres"];
  "?Grindcore"->"?Noise_rock"[label="dbo:stylisticOrigin"];
  "?Noise_rock"->"?Noise_music"[label="dbp:stylisticOrigins"];
  "?Electronic_rock"->"?Rock_music"[label="dbp:stylisticOrigins"];
}

SELECT  *
WHERE
{
  ?Noise_pop  <http://dbpedia.org/property/localScenes>  ?Group429 .
  ?Noise_rock  <http://dbpedia.org/property/fusiongenres>  ?Noise_pop .
  ?Grindcore  <http://dbpedia.org/ontology/stylisticOrigin>  ?Noise_rock .
  ?Electronic_rock
      <http://dbpedia.org/ontology/musicSubgenre>  ?Grindcore ;
      <http://dbpedia.org/property/stylisticOrigins>  ?Rock_music .
  ?Noise_rock  <http://dbpedia.org/property/stylisticOrigins>  ?Noise_music
}

digraph{
"?Phoenician_alphabet"->"?Group15"[label="dbp:fam"];
"?Phoenician_alphabet"->"?Proto-Sinaitic_script"[label="dbp:fam"];
"?Cyrillic_script"->"?Group15"[label="dbp:fam"];
"?Proto-Sinaitic_script"->"?Group15"[label="dbp:fam"];
"?Oklahoma"->"?Cherokee_language"[label="dbo:language"];
"?Cyrillic_script"->"?Group636"[label="dbp:fam"];
"?Phoenician_alphabet"->"?Group2016"[label="dbp:fam"];
"?Proto-Sinaitic_script"->"?Group636"[label="dbp:fam"];
"?Latin_script"->"?Group1809"[label="dbp:fam"];
"?Cyrillic_script"->"?Group774"[label="dbp:fam"];
"?Texas"->"?Organisation489"[label="dbp:lowerhouse"];
"?Cyrillic_script"->"?Group2016"[label="dbp:fam"];
"?Proto-Sinaitic_script"->"?Group498"[label="dbp:fam"];
"?Texas"->"?_Texas"[label="dbo:capital"];
"?George_W_Bush"->"?Sport761"[label="dbo:profession"];
"?Proto-Sinaitic_script"->"?Group1809"[label="dbp:fam"];
"?Phoenician_alphabet"->"?Group1809"[label="dbp:fam"];
"?Cyrillic_script"->"?Coptic_alphabet"[label="dbp:sisters"];
"?Cyrillic_script"->"?Proto-Sinaitic_script"[label="dbp:fam"];
"?George_W_Bush"->"?PoliticalParty560"[label="dbp:party"];
"?_Texas"->"?Texas"[label="dbo:isPartOf"];
"?Brian_Sandoval"->"?George_W_Bush"[label="dbp:nominator"];
"?George_W_Bush"->"?Ann_Richards"[label="dbo:predecessor"];
"?Cherokee_language"->"?Latin_script"[label="dbp:script"];
"?Cyrillic_script"->"?Phoenician_alphabet"[label="dbp:fam"];
"?Phoenician_alphabet"->"?Group498"[label="dbp:fam"];
"?Ann_Richards"->"?Texas"[label="dbo:birthPlace"];
"?Texas"->"?Oklahoma"[label="dbp:borderingstates"];
"?George_W_Bush"->"?Sport554"[label="dbo:profession"];
"?Latin_script"->"?Cyrillic_script"[label="dbp:sisters"];
}
SELECT  *
WHERE
  { ?Texas    <http://dbpedia.org/property/lowerhouse>  ?Organisation489 .
    ?Oklahoma  <http://dbpedia.org/ontology/language>  ?Cherokee_language .
    ?_Texas   <http://dbpedia.org/ontology/isPartOf>  ?Texas .
    ?Cyrillic_script
              <http://dbpedia.org/property/fam>  ?Group15 .
    ?Latin_script
              <http://dbpedia.org/property/fam>  ?Group1809 .
    ?Texas    <http://dbpedia.org/ontology/capital>  ?_Texas .
    ?Proto_Sinaitic_script
              <http://dbpedia.org/property/fam>  ?Group498 .
    ?George_W_Bush
              <http://dbpedia.org/ontology/profession>  ?Sport761 .
    ?Texas    <http://dbpedia.org/property/borderingstates>  ?Oklahoma .
    ?Phoenician_alphabet
              <http://dbpedia.org/property/fam>  ?Group2016 ;
              <http://dbpedia.org/property/fam>  ?Proto_Sinaitic_script .
    ?Ann_Richards
              <http://dbpedia.org/ontology/birthPlace>  ?Texas .
    ?Brian_Sandoval
              <http://dbpedia.org/property/nominator>  ?George_W_Bush .
    ?Proto_Sinaitic_script
              <http://dbpedia.org/property/fam>  ?Group1809 .
    ?Cyrillic_script
              <http://dbpedia.org/property/fam>  ?Phoenician_alphabet ;
              <http://dbpedia.org/property/fam>  ?Group636 .
    ?George_W_Bush
              <http://dbpedia.org/ontology/predecessor>  ?Ann_Richards .
    ?Latin_script
              <http://dbpedia.org/property/sisters>  ?Cyrillic_script .
    ?George_W_Bush
              <http://dbpedia.org/ontology/profession>  ?Sport554 .
    ?Cherokee_language
              <http://dbpedia.org/property/script>  ?Latin_script .
    ?Phoenician_alphabet
              <http://dbpedia.org/property/fam>  ?Group1809 .
    ?Proto_Sinaitic_script
              <http://dbpedia.org/property/fam>  ?Group636 .
    ?Phoenician_alphabet
              <http://dbpedia.org/property/fam>  ?Group15 ;
              <http://dbpedia.org/property/fam>  ?Group498 .
    ?Cyrillic_script
              <http://dbpedia.org/property/fam>  ?Group774 ;
              <http://dbpedia.org/property/fam>  ?Proto_Sinaitic_script ;
              <http://dbpedia.org/property/sisters>  ?Coptic_alphabet .
    ?George_W_Bush
              <http://dbpedia.org/property/party>  ?PoliticalParty560 .
    ?Cyrillic_script
              <http://dbpedia.org/property/fam>  ?Group2016 .
    ?Proto_Sinaitic_script
              <http://dbpedia.org/property/fam>  ?Group15
  }
