03/Jan/2014 15:00:00  0100 SELECT DISTINCT ?Museum (SAMPLE(?name) as ?name) (SAMPLE(?abstract) as ?abstract) (SAMPLE(?thumbnail) as ?thumbnail) (MAX(?latitude) as ?latitude) (MAX(?longitude) as ?longitude) (SAMPLE(?established) as ?established) (SAMPLE(?website) as ?website) (SAMPLE(?homepage) as ?homepage) (SAMPLE(?wikilink) as ?wikilink) WHERE { ?Museum a dbpedia-owl:Museum ;          dbpprop:name ?name ; dbpedia-owl:abstract ?abstract ; dbpedia-owl:thumbnail ?thumbnail ;  geo:lat ?latitude ; geo:long ?longitude ; dbpprop:established ?established; dbpprop:website ?website ; foaf:homepage ?homepage ; foaf:isPrimaryTopicOf ?wikilink . FILTER(langMatches(lang(?abstract),"ES"))   } GROUP BY ?Museum  LIMIT 10 OFFSET 0


prefix dbp:<http://dbpedia.org/ontology/>
select ?athleteGroupEN (count(?athlete) as ?count) (avg(?age) as ?ageAvg)
    where {
        filter(?age >= 20 && ?age <= 100) .
        {
            select distinct ?athleteGroupEN ?athlete (?deathYear - ?birthYear as ?age)
                where {
                    ?subOfAthlete rdfs:subClassOf dbp:Athlete .
                        ?subOfAthlete rdfs:label ?athleteGroup filter(lang(?athleteGroup) = "en") .
                        bind(str(?athleteGroup) as ?athleteGroupEN)
                        ?athlete a ?subOfAthlete .
                        ?athlete dbp:birthDate ?birth filter(datatype(?birth) = xsd:date) .
                        ?athlete dbp:deathDate ?death filter(datatype(?death) = xsd:date) .
                        bind (strdt(replace(?birth,"^(\\d+)-.*","$1"),xsd:integer) as ?birthYear) .
                        bind (strdt(replace(?death,"^(\\d+)-.*","$1"),xsd:integer) as ?deathYear) .
                }
        }
    } group by ?athleteGroupEN having (count(?athlete) >= 25) order by ?ageAvg


prefix dcterms:<http://purl.org/dc/terms/>
prefix dbr:<http://dbpedia.org/resource/>
select ?showB ?subjCountShowAB ?subjCountShowA ?subjCountShowB (strdt(?subjCountShowAB,xsd:double) / (?subjCountShowA + ?subjCountShowB - ?subjCountShowAB) as ?subjScore)
    where {
        {
            select ?showB ?subjCountShowAB ?subjCountShowA (count(?subject) as ?subjCountShowB)
                where {
                    ?showB dcterms:subject ?subject .
                    {
                        select ?showB (count(?subject) as ?subjCountShowAB) ?subjCountShowA
                            where {
                                ?showA dcterms:subject ?subject .
                                    ?showB dcterms:subject ?subject filter(!sameTerm(?showA,?showB)) .
                                    {
                                        select ?showA (count(?subject) as ?subjCountShowA)
                                            where {
                                                ?showA dcterms:subject ?subject filter(sameTerm(?showA,dbr:Friends)) .
                                            }
                                    }
                            } group by ?showB ?subjCountShowA
                    }
                } group by ?showB ?subjCountShowAB ?subjCountShowA
        }
    } order by desc(?subjScore) limit 100


select *
where {
    ?p rdfs:range ?range.
        FILTER regex(?range, "^http://www.w3.org/2001/XMLSchema#", "i")
        {
            select distinct ?p
                where {
                    ?p rdf:type rdf:Property.
                }
            #limit 1000
        }
} order by ?range

SELECT *
WHERE
{?p rdfs:range ?range. FILTER regex(?range, "^http://www.w3.org/2001/XMLSchema#", "i")
    {SELECT ?p
        WHERE { [] a dbo:Person; ?p [].
            {SELECT DISTINCT ?p
                WHERE {
                    ?p rdf:type rdf:Property.
                }
            }
        }
    }
}

SELECT DISTINCT ?p1 ?c1 ?p2 ?c2 ?p3 ?c3 ?p4 ?c4 ?p5
CONSTRUCT
{
  dbo:Person ?p1 ?c1.
  ?c1 ?p2 ?c2.
  ?c2 ?p3 ?c3.
  ?c3 ?p4 ?c4.
  ?c4 ?p5 dbo:Event.
}
WHERE
{
  ?s a dbo:Person.
  ?e a dbo:Event.

  ?n1 a ?c1.
  ?n2 a ?c2.
  ?n3 a ?c3.
  ?n4 a ?c4.

  FILTER (!sameTerm(?c1, owl:Thing))
  FILTER (!sameTerm(?c2, owl:Thing))
  FILTER (!sameTerm(?c3, owl:Thing))
  FILTER (!sameTerm(?c4, owl:Thing))

  ?s ?p1 ?n1.
  ?n1 ?p2 ?n2.
  ?n2 ?p3 ?n3.
  ?n3 ?p4 ?n4.
  ?n4 ?p5 ?e.
}

#ci4c 398776089  239/100000
SELECT (COUNT (DISTINCT *) AS ?count)
WHERE
{
  SELECT REDUCED ?n1 ?n2 ?n3 ?n4 ?p1 ?p2 ?p3 ?p4 ?p5
  WHERE
  {
    ?s a dbo:Person.
    ?e a dbo:Event.

    ?n1 a ?c1.
    ?n2 a ?c2.
    ?n3 a ?c3.
    ?n4 a ?c4.

    FILTER (!sameTerm(?c1, owl:Thing))
    FILTER (!sameTerm(?c2, owl:Thing))
    FILTER (!sameTerm(?c3, owl:Thing))
    FILTER (!sameTerm(?c4, owl:Thing))

    ?s ?p1 ?n1.
    ?n1 ?p2 ?n2.
    ?n2 ?p3 ?n3.
    ?n3 ?p4 ?n4.
    ?n4 ?p5 ?e.
  }
}

#c6 3802341 100000/100000
SELECT (COUNT (DISTINCT *) AS ?count)
WHERE
{
  SELECT REDUCED ?c1 ?c2 ?c3 ?c4 ?p1 ?p2 ?p3 ?p4 ?p5
  WHERE
  {
    ?s a dbo:Person.
    ?e a dbo:Event.

    ?n1 a ?c1.
    ?n2 a ?c2.
    ?n3 a ?c3.
    ?n4 a ?c4.

    FILTER (!sameTerm(?c1, owl:Thing))
    FILTER (!sameTerm(?c2, owl:Thing))
    FILTER (!sameTerm(?c3, owl:Thing))
    FILTER (!sameTerm(?c4, owl:Thing))

    ?s ?p1 ?n1.
    ?n1 ?p2 ?n2.
    ?n2 ?p3 ?n3.
    ?n3 ?p4 ?n4.
    ?n4 ?p5 ?e.
  }
}

#i* 467105204
SELECT (COUNT (*) AS ?count)
WHERE
{
  ?s a dbo:Person.
  ?e a dbo:Event.

  ?n1 a ?c1.
  ?n2 a ?c2.
  ?n3 a ?c3.
  ?n4 a ?c4.

  FILTER (!sameTerm(?c1, owl:Thing))
  FILTER (!sameTerm(?c2, owl:Thing))
  FILTER (!sameTerm(?c3, owl:Thing))
  FILTER (!sameTerm(?c4, owl:Thing))

  ?s ?p1 ?n1.
  ?n1 ?p2 ?n2.
  ?n2 ?p3 ?n3.
  ?n3 ?p4 ?n4.
  ?n4 ?p5 ?e.
}
